from enum import Enum

class EnumCoachingCategory(Enum):
    MISSION_SUPPORT = "MISSION_SUPPORT"
    COMMUNICATION_SUPPORT = "COMMUNICATION_SUPPORT"
    IT_SUPPORT = "IT_SUPPORT"
    INTERVIEW_SUPPORT = "INTERVIEW_SUPPORT"
    OTHER_SUPPORT = "OTHER_SUPPORT"