from enum import Enum


class ExperienceLevel(Enum):
    ZERO_TO_ONE_YEAR = 'ZERO_TO_ONE_YEAR'
    TWO_TO_THREE_YEARS = "TWO_TO_THREE_YEARS"
    FOUR_TO_SIX_YEARS = "FOUR_TO_SIX_YEARS"
    SEVEN_TO_TEN_YEARS = "SEVEN_TO_TEN_YEARS"
    TEN_PLUS_YEARS = "TEN_PLUS_YEARS"