from enum import Enum


class EnumFilterType(str, Enum):
    BANK_TRANSACTIONS = 'BANK_TRANSACTIONS'
    RUN_INVOICE_CONTENTS = "RUN_INVOICE_CONTENTS",
    PRINTED_INVOICES = "PRINTED_INVOICES",
    MISSIONS = "MISSIONS"