from enum import Enum

class EnumWithdrawRequestStatus(Enum):
    APP_ACCEPTED = "APP_ACCEPTED" 
    APP_REFUSED = "APP_REFUSED"
    APP_PENDING = "APP_PENDING"   
    APP_CANCELED = "APP_CANCELED"   
    STRIPE_PAID = "STRIPE_PAID"
    STRIPE_PENDING = "STRIPE_PENDING"
    STRIPE_IN_TRANSIT = "STRIPE_IN_TRANSIT"  
    STRIPE_CANCELED = "STRIPE_CANCELED"   
    STRIPE_FAILED = "STRIPE_FAILED"