SYSTEM_SUPPLIER = 'SYSTEM'


#INVOICE CLASS CODE
EXPENSE_NOTES = 'EXPENSE_NOTES'
PAY_STATEMENTS = 'PAY_STATEMENTS'
TRANSPORT_PROOFS = 'TRANSPORT_PROOFS'
EATERY_VOUCHERS = 'EATERY_VOUCHERS'
RELEVE_DE_COMPTES = 'RELEVE_DE_COMPTES'
